# Generated by Django 4.2.11 on 2024-03-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=30, unique=True)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('cast', models.TextField(blank=True)),
                ('imdb_rating', models.IntegerField()),
                ('trailer_link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='image')),
                ('slug', models.SlugField()),
                ('comments_or_review', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
